### ISSUE TITLE
Add a sentence describing each Param 

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/Token-Log-Hatch-Params#166]
All the content can be pulled from: https://forum.tecommons.org/t/tec-test-hatch-implementation-specification/226

Add the sentance under the param name above the param input

**Comment by kristoferlund** [comment]
I found a way to add description texts thats was not overly hacky. It's not beautiful but it works.. It could have worked.

But.. In order to fit the text I have to add to the margins of the inputs (using the method provided by Panels). But, this added height is not taken into account when Panel calculates the abs height of the surrounding div. So, the layout of the rest of the page unfortunately breaks. 😬  See below, "Run simulation" button ends up on top of the table down there.

![image](https://user-images.githubusercontent.com/9698363/114031549-c77a1c00-987b-11eb-92ea-aa89cf11bbdb.png)

Commit on separate branch here: https://github.com/CommonsBuild/Token-Log-Hatch-Params/commit/67e0f10171faf0b8cf00c57347aceb2b1bc12bb4

I'll have another look at it tomorrow but it seems difficult to solve this without having to write new slider components that support description texts. Is that possible, I don't know. Tbc..

**Comment by mendesfabio** [comment]
@kristoferlund I think I found a good way to make it, check the image below. We've been trying to fix this one for a long time since Panel doesn't provide us any kind of tooltip. I had this idea with @marthendalnunes this morning and opened the PR #179.

![image](https://user-images.githubusercontent.com/43360747/114076798-766b2780-987d-11eb-9815-528855ad67b0.png)

**Comment by mendesfabio** [comment]
We just need to figure out how to fix the width of each component.

**Comment by kristoferlund** [comment]
That looks great!
