### ISSUE TITLE
Add tooltips to the params sliders

### ISSUE THREAD

**Issue by marthendalnunes** [CommonsBuild/Token-Log-Hatch-Params#56]
As pointed by @markoprljic, we should have simple tooltips for every parameter to clarify for the hatchers the meaning of the parameter into the dashboard, without needing to go to the forum. Although, it still makes sense to add the links to the forum for a deep dive on each param.

**Comment by marthendalnunes** [comment]
https://panel.holoviz.org/reference/widgets/IntSlider.html

![image](https://user-images.githubusercontent.com/18421017/108364149-7da67b00-71d4-11eb-8c7f-9270dd5e5d6b.png)

**Comment by marthendalnunes** [comment]
This might worth trying: https://discourse.holoviz.org/t/how-to-create-a-conditional-custom-hover-tool-for-a-holoviews-plot/311/2

**Comment by Jeff-Emmett** [comment]
Happy to help with glossary / terminology definitions, if needed!

**Comment by markoprljic** [comment]
> Happy to help with glossary / terminology definitions, if needed!

Thanks Jeff, would be great to do a quick sesh on that.

**Comment by markoprljic** [comment]
Hey @Jeff-Emmett I noticed that Jake started working on a similar issue explaining the Hatch params https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/tecommons/coordination/149

I was thinking if you could maybe hack on this doc (or start fresh) making a list of params and writing a short description of each. We could potentially close **three** issues at the same time: 
1. Have the TLDR for params
2. Have content for tooltips
3. Have content for more explanation to put on the Hatch Dashboard

Please let me know about this so we can coordinate. Thanks a lot!

**Comment by markoprljic** [comment]
@marthendalnunes @mendesfabio I know we talked about tooltips and that we cannot add them, but I'm keeping this issue open and inside the epic because of the content that is still required for other stuff and my ask from @Jeff-Emmett to assist.

**Comment by Jeff-Emmett** [comment]
I forked Jakes doc and started a Hatch Params Glossary doc here: https://docs.google.com/document/d/1rNE37FvYxkNSbIRvYXTQlOReJzXExUq_IDYv4Oem4NE/edit?usp=sharing

I noticed that the params listed in Jake's doc no longer match up with the params in the dashboard, and that the dashboard itself is still changing, so I won't continue on the glossary for the time being (especially with other time commitments taking priority for the moment).

Tbh, I believe some of these params should be split out into different dashboards, or perhaps different parts of the same dashboard connected via hyperlink. Some of the params pertaining solely to the TEC (that won't be replicable with other Commons launches) e.g. Impact Hours params could likely be determined by a smaller group of people without having to expose our entire audience to the detailed intricacies of how much early contributors should be compensated for their work. No one outside of that group is likely to care, imho.

I think the external-facing dashboard should focus on core system parameters, like configuring Dandelion Voting, ABC & CV, and other replicable components of Commons ecosystems etc. Adding too many extra params on top of this is likely to confuse and repel a larger audience. (I am probably considered a close contributor, and even I can't make sense of some of the params for IH - e.g. IH curvature??  Are we configuring bonding curves already?  This is going to confuse people who think that's what we're asking! TMI to the max on a minor consideration that is custom built for this launch and won't be used elsewhere)

I also think we should talk about rage quitting, redeemable DAI & refunds NOT as primary system components, but rather as options for people who disagree and choose to leave.  When I look into subscribing for a new service in the real world, the first thing I want to be told is what benefits I am going to derive from the service, rather than how I can get my money back. I don't think we need to emphasize the Hatch Tribute either, except in the case of Rage Quitting where it is essentially a fee for backing out. Calling it a tribute when it doesn't share the properties of other tributes in our system (e.g. Exit Tribute, which is a % of funds withdrawn) is likely to be confusing for our audience.

I'm happy to stay in the loop on dashboard development, but I think it's important to make sure we take our "engineers who love parameters" hats off and put our "humans who don't know anything about this system" hats on to look at it with fresh eyes every now and again. I also think we need to ground these params in a larger system diagram - what component of the system are the parameters under discussion for? Context is king!  (I've been doing some diagramming for these considerations but can't afford the time to take them to completion - if this group finds them helpful, I'd be happy to advise on next steps for diagramming: https://miro.com/app/board/o9J_krl8Cv0=/?moveToWidget=3074457355266047085&cot=14)

**Comment by markoprljic** [comment]
> I forked Jakes doc and started a Hatch Params Glossary doc here: https://docs.google.com/document/d/1rNE37FvYxkNSbIRvYXTQlOReJzXExUq_IDYv4Oem4NE/edit?usp=sharing

Thank you Jeff! :)

> 
> I noticed that the params listed in Jake's doc no longer match up with the params in the dashboard, and that the dashboard itself is still changing, so I won't continue on the glossary for the time being (especially with other time commitments taking priority for the moment).
> 
Yes, indeed it is changing, it's still being developed.

> Tbh, I believe some of these params should be split out into different dashboards, or perhaps different parts of the same dashboard. Some of the params pertaining solely to the TEC (that won't be replicable with other Commons launches) e.g. Impact Hours params could likely be determined by a smaller group of people without having to expose our entire audience to the detailed intricacies of how much early contributors should be compensated for their work. No one outside of that group is likely to care, imho.
> 
Hmmm, I thought this was supposed to be used by us at first to share our params and results with others before the Hatch? I'm not 100% sure on this. 
After that hatch, for the general audience maybe it should be left out.

> I think the dashboard should focus on core system parameters, like configuring Dandelion Voting, ABC & CV, and other replicable components of Commons ecosystems etc. Adding too many extra params on top of this is likely to confuse and repel a larger audience. (I am probably considered a close contributor, and even I can't make sense of some of the params for IH - e.g. IH curvature? Are we configuring bonding curves already? This is going to confuse people who think that's what we're asking imo).
> 
The whole dashboard and params are already confusing for general public, I consider myself a great persona to test this hahahaha. I'm definitely looking for ways to simplify it and educate users on the spot so that they are able to use the dashboard right away even having little understanding of params beforehand. 

> I also think we should talk about rage quitting, redeemable DAI & refunds NOT as primary system components, but rather as options for people who disagree and choose to leave. When I look into subscribing for a new service in the real world, the first thing I want to be told is what benefits I am going to derive from the service, rather than how I can get my money back. I don't think we need to emphasize the Hatch Tribute either, except in the case of Rage Quitting where it is essentially a fee for backing out. Calling it a tribute when it doesn't share the properties of other tributes in our system (e.g. Exit Tribute, which is a % of funds withdrawn) is likely to be confusing for our audience. It also isn't relevant to anyone who isn't rage quitting(?).
> 
Ok. 

> I'm happy to stay in the loop on dashboard development, but I think it's important to make sure we take our "engineers who love parameters" hats off and put our "humans who don't know anything about this system" hats on to look at it with fresh eyes every now and again. 
>
Totally agree!

> I also think we need to ground these params in a larger system diagram - what component of the system are the parameters under discussion for? Context is king! (I've been doing some diagramming for these considerations but haven't found the time to take them to completion - if this group finds them helpful, I'd be happy to work with someone on next steps for diagramming: https://miro.com/app/board/o9J_krl8Cv0=/?moveToWidget=3074457355266047085&cot=14)
>
Thanks for sharing this. I wonder how we could turn this into something digestable or integrated in any other way in the Dashboard? 

Thanks again for all this Jeff, it helps a lot.

**Comment by LinuxIsCool** [comment]
Here is an example of adding custom tool tips to holoviews charts. I'm not sure if this will help us with tool tips on the sliders themselves. Maybe tool tips on the charts will be sufficient, we can explain the relevant parameters that go into the chart. 

https://discourse.holoviz.org/t/how-to-create-a-conditional-custom-hover-tool-for-a-holoviews-plot/311/2

**Comment by LinuxIsCool** [comment]
This open on panel is requesting tooltip functionality on sliders: 

https://github.com/holoviz/panel/issues/1298

**Comment by LinuxIsCool** [comment]
Here is the Holoviews documentation on custom tooltips:  
http://holoviews.org/user_guide/Plotting_with_Bokeh.html

And here is the full bokeh documentation on tooltips:  
https://docs.bokeh.org/en/latest/docs/user_guide/tools.html#hovertool

**Comment by LinuxIsCool** [comment]
OK, so I think I see how to do it now. We are going to put tooltips on the charts. I'll make examples of how this works on the current charts, and I will see if I can pull out the content data into the dictionary config file that Vitor has made.

**Comment by freedumbs00** [comment]
@mendesfabio Great job!!  closing this issue
